artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/feyisayoav/Datasets/raw/main/Chicken_Data.zip
  local_data_file: artifacts/data_ingestion/Chicken_Data.zip
  unzip_dir: artifacts/data_ingestion
